services:
  rezume:
    image: nginx:stable-alpine
    container_name: resume-web
    network_mode: host
    restart: unless-stopped

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./site:/var/www/resume:ro