server {
    listen 127.0.0.1:8088;
    server_name sv.bastion-local.ru;
    
    root /var/www/current;
    index index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }

}